version: '3.4'

services:
  gbsodev-techtest-library-web:
    image: gbsodev/gbsodev-techtest-library-web:release
    hostname: library-web
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: production
    ports:
      - 80:80
  gbsodev-techtest-library-webapi:
    image: gbsodev/gbsodev-techtest-library-webapi:release
    hostname: library-webapi
    expose:
      - 443
      - 80
