version: '3.4'

services:
  gbsodev-techtest-library-web:
    image: gbsodev/gbsodev-techtest-library-web:release
    hostname: library-web
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: production
    ports:
      - 8080:80
